name: renovate-config-validator

on:
  pull_request:
    paths:
      - "default.json"
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - "default.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3