name: Renovate Config Validator

on:
  workflow_call:
    inputs:
      config_file_path:
        description: "Config file to validate. Not needed in normal usage, by default standard renovate config locations are searched."
        required: false
        default: ""
        type: string

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
        with:
          config_file_path: ${{ inputs.config_file_path }}
